import { expect, test } from '@playwright/test'

test('edits a person, undoes/redoes, and restores the local draft', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Всё дерево' })).toBeVisible()
  await page.getByRole('button', { name: 'К первой карточке' }).click()
  const panel = page.getByRole('complementary', { name: 'Карточка человека' })
  await expect(panel.getByLabel('Имя', { exact: true })).toHaveValue('Александр')
  await panel.getByLabel('Имя', { exact: true }).fill('Тестовое имя')
  await panel.getByRole('button', { name: 'Применить изменения' }).click()
  await expect(panel.getByRole('heading', { name: 'Тестовое имя Леснов' })).toBeVisible()
  await page.getByRole('button', { name: 'Отменить изменение', exact: true }).click()
  await expect(panel.getByLabel('Имя', { exact: true })).toHaveValue('Александр')
  await page.getByRole('button', { name: 'Повторить изменение', exact: true }).click()
  await expect(panel.getByLabel('Имя', { exact: true })).toHaveValue('Тестовое имя')
  await expect(page.getByTestId('save-status')).toContainText('Сохранено')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Всё дерево' })).toBeVisible()
  await expect(page.getByTestId('layout-time')).toContainText('Расположение восстановлено')
  await page.getByLabel('Поиск человека').fill('I0001')
  await page.getByRole('button', { name: /Тестовое имя Леснов/ }).click()
  await expect(panel.getByLabel('Имя', { exact: true })).toHaveValue('Тестовое имя')
  await expect(page.locator('.canvas-controls')).toContainText('100%')
  await expect(page.locator('.react-flow__node-person[data-id="I0001"]')).toBeInViewport()
  await expect(page.getByTestId('save-status')).toContainText('Сохранено')
  expect(errors).toEqual([])
  await page.screenshot({ path: 'test-results/editor-card.png' })
})

test('loads all 3000 people and navigates to the last person', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('dialog', (dialog) => dialog.accept())
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Всё дерево' })).toBeVisible()
  const started = Date.now()
  await page.getByLabel('Демонстрационное дерево').selectOption('3000')
  await expect(page.getByRole('button', { name: 'Всё дерево' })).toBeVisible({ timeout: 60_000 })
  await expect(page.getByTestId('save-status')).toContainText('Сохранено', { timeout: 30_000 })
  const readyMs = Date.now() - started
  const layout = await page.getByTestId('layout-time').textContent()
  await page.getByLabel('Поиск человека').fill('I3000')
  await page.getByRole('button', { name: /I3000/ }).click()
  const panel = page.getByRole('complementary', { name: 'Карточка человека' })
  await expect(panel).toContainText('I3000')
  await expect(page.locator('.canvas-controls')).toContainText('100%')
  await expect(page.locator('.react-flow__node-person[data-id="I3000"]')).toBeInViewport()
  await panel.getByLabel('Заметка').fill('Последняя карточка тоже редактируется')
  await panel.getByRole('button', { name: 'Применить изменения' }).click()
  await expect(page.getByTestId('save-status')).toContainText('Сохранено')
  await expect(page.getByTestId('layout-time')).toHaveText(layout!)
  await page.getByRole('button', { name: 'Всё дерево' }).click()
  await expect(page.locator('.react-flow__node-person')).toHaveCount(3000, { timeout: 30_000 })
  const metrics = { browser: await page.evaluate(() => navigator.userAgent), readyMs, layout, visibleCards: await page.locator('.react-flow__node-person').count() }
  await testInfo.attach('large-tree-metrics', { body: JSON.stringify(metrics, null, 2), contentType: 'application/json' })
  console.log(JSON.stringify(metrics))
  expect(errors).toEqual([])
  await page.screenshot({ path: 'test-results/tree-3000.png' })
})

test('guards unsaved form edits and supports downloading/restoring a draft', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Всё дерево' })).toBeVisible()
  await page.getByRole('button', { name: 'К первой карточке' }).click()
  await page.getByLabel('Имя', { exact: true }).fill('Неприменённое имя')
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: 'Закрыть карточку' }).click()
  await expect(page.getByLabel('Имя', { exact: true })).toHaveValue('Неприменённое имя')
  await page.getByRole('button', { name: 'Применить изменения' }).click()
  await page.getByLabel('Меню черновика').click()
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать копию' }).click()
  const file = await downloaded
  const path = await file.path()
  page.on('dialog', (dialog) => dialog.accept())
  await page.locator('input[accept=".json,application/json"]').setInputFiles(path!)
  await expect(page.getByRole('button', { name: 'Всё дерево' })).toBeVisible()
  await page.getByRole('button', { name: 'К первой карточке' }).click()
  await expect(page.getByLabel('Имя', { exact: true })).toHaveValue('Неприменённое имя')
})
